const user = [
	{
		name: "Ripon Miah",
		age: 28,
		cell: "0191359868",
		gender: "male",
		Location: "Dhaka",
		skill: "Laravel Developer",
		mail: "laraveldev@gmail.com",
	},
	{
		name: "Mony Akter",
		age: 28,
		cell: "01966060192",
		gender: "female",
		Location: "Gazipur",
		skill: "Mern Stack Developer",
		mail: "mony@gmail.com",
	},
	{
		name: "Abu Rayhan",
		age: 36,
		cell: "01990449319",
		gender: "male",
		Location: "Sherpur",
		skill: "Php Developer",
		mail: "aburayhan@gmail.com",
	},
	{
		name: "Mim akter Mimi",
		age: 23,
		cell: "01966063434",
		gender: "female",
		Location: "Uttara",
		skill: "Laravel Developer",
		mail: "mimi@gmail.com",
	},
	{
		name: "Shopon Chowdhury",
		age: 35,
		cell: "0141359868",
		gender: "male",
		Location: "Dhaka",
		skill: "Laravel Developer",
		mail: "shopon@gmail.com",
	},
];
